# Generated by Django 5.1.5 on 2025-06-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="key_analysismodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("political_name", models.CharField(max_length=5)),
                ("political_keyword", models.CharField(max_length=30)),
                ("political_issue", models.CharField(max_length=30)),
                ("issue_count", models.IntegerField()),
            ],
        ),
    ]
