# Generated by Django 5.1.5 on 2025-06-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="key_analysismodel",
        ),
    ]
